### ISSUE TITLE
Incompatible with Ghidra 10.1.3

### ISSUE THREAD

**Issue by muffinjets** [pudii/gba-ghidra-loader#2]

**Comment by pudii** [comment]
Hi, thanks for the issue. Can you provide more information? 

Does is also not work if you compile it from source or is just the released file not working?

**Comment by muffinjets** [comment]
Hi, sorry for the late response

I'm using the release file, not sure how to build from source

It wasn't a big deal, I just downgraded to 10.1.2 for what I had to use it for.

The specific error I ran into was attempted to install the extension in 10.1.3, Ghidra responded with the incompatibility message.

**Comment by pudii** [comment]
This is expected behaviour, as the releases are built for specific Ghidra versions and don't work on others. Hence the steps in the README to build from source.

I'll try to release updated versions, but I can't guarantee, because Ghidra releases new versions frequently.

**Comment by HimoriK** [comment]
@muffinjets To anyone that can't build it or to use the release with any version of Ghidra, open the 'extension' file and change the version to whatever you're running ex. '10.3.2'. To build on Windows download Gradle and it's path, then in cmd do 'gradle -PGHIDRA_INSTALL_DIR=C:\ghidra'. If successful it will be in dist.
