### ISSUE TITLE
It doesn't work with Ghidra 10.2

### ISSUE THREAD

**Issue by Temporalin** [pudii/gba-ghidra-loader#3]
Can't compile for Ghidra 10.2 because there's a class missing. That class has been refactored:

https://github.com/NationalSecurityAgency/ghidra/issues/4730

**Comment by pudii** [comment]
Hey, thanks for bringing this up! I will take a look at it.

**Comment by L0rdS474n** [comment]
When this is looked at, could you look at the address issue too?
I'm not yet comfortable to do loaders so I will wait for you to fix this time 😁

**Comment by pudii** [comment]
Thanks guys! This looks good.

**Comment by pudii** [comment]
> When this is looked at, could you look at the address issue too?
> I'm not yet comfortable to do loaders so I will wait for you to fix this time 😁

Hey @port513, please check if anything works for you now. The address issue should be fixed in https://github.com/pudii/gba-ghidra-loader/commit/8c5a5f8bffabac929eaa1a571ad5e0d672b24101.

**Comment by L0rdS474n** [comment]
Will check it in a few hours, I eyed the code and it looks as if it is fixed but I will test it out today.
